---
title: "p8105_hw3_sal2222"
author: "Stephen Lewandowski"
date: "October 15, 2018"
output: html_document
---


```{r setup, include = FALSE}

library(tidyverse)
library(readxl)
library(devtools)
library(p8105.datasets) #devtools::install_github("p8105/p8105.datasets")

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# Problem 1


I will load and format the Behavioral Risk Factors Surveillance System (BRFSS) for Selected Metropolitan Area Risk Trends (SMART) data from the p8105.datasets package.

```{r load BRFSS}

data("brfss_smart2010")
brfss <- brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  select(-c(class, topic, question, sample_size, confidence_limit_low:geo_location)) %>% 
  spread(key = response, value = data_value) %>% 
  janitor::clean_names() %>% 
  rename(state = locationabbr, county = locationdesc) %>% 
  separate(county, into = c("remove", "county"), sep = "- ") %>%
  select(year, state, county, poor, fair, good, very_good, excellent)
  
brfss
   
```


I will answer questions using this BRFSS dataset.



